name: XzAffinity
version: 1.0.0
api: 5.0.0
main: IndraMC\XzAffinity\Main
author: IndraMC
description: Affinity system for PocketMine-MP servers
depend: [FormAPI]

permissions:
  xzaffinity.command.use:
    description: Allows using the affinity command
    default: true
  xzaffinity.command.admin:
    description: Allows using the affinity admin command
    default: op
